### ISSUE TITLE
The scheduled job of type 'Geta.GoogleProductFeed.FeedBuilderCreateJob' cannot be created. It must either be registered in the IOC container or have a default constructor.

### ISSUE THREAD

**Issue by chiching1119** [Geta/GoogleProductFeed#5]
Hi, 
I have installed Geta.GoogleProductFeed in my episerver project and tried to run the job "Google ProductFeed - Create feed". 

I got the following error: 
UnableToStart - The scheduled job of type 'Geta.GoogleProductFeed.FeedBuilderCreateJob' cannot be created. It must either be registered in the IOC container or have a default constructor.

What I have done is implemented EpiFeedBuilder class and added 
container.For<FeedBuilder>().Use<EpiFeedBuilder>(); to my DependencyResolverInitialization.

Any tips how to solve the issue?

**Comment by frederikvig** [comment]
Which version of Episerver are you running?

**Comment by chiching1119** [comment]
Hi, the site is running 11.9.1.
I created EpiFeedBuilder implement the abstract class FeedBuilder and the method Build.
Then I added  **container.For<FeedBuilder>().Use<EpiFeedBuilder>();**
in the DependencyResolverInitialization class.
    {
        public void ConfigureContainer(ServiceConfigurationContext context)
        {
            var container = context.StructureMap();

            container.Configure(ConfigureContainer);
            var resolver = new StructureMapDependencyResolver(container);

            DependencyResolver.SetResolver(resolver);
            GlobalConfiguration.Configuration.DependencyResolver = resolver;
        }

        private static void ConfigureContainer(ConfigurationExpression container)
        {
         ....
            container.For<FeedBuilder>().Use<EpiFeedBuilder>();
          ....
        }

**Comment by frederikvig** [comment]
My guess is that that the DependencyResolverInitialization might not be kicking in. Could you check the logs to make sure?

**Comment by chiching1119** [comment]
I check the episerver error log. 

2018-12-10 14:52:50,930 [112] ERROR EPiServer.DataAbstraction.ScheduledJob: Failed to create job instance for 'Google ProductFeed - Create feed' with jobId = '4ef955ec-72f2-41e2-b990-5dbe1fe1583a'
System.InvalidOperationException: The scheduled job of type 'Geta.GoogleProductFeed.FeedBuilderCreateJob' cannot be created. It must either be registered in the IOC container or have a default constructor.
   at EPiServer.Scheduler.Internal.DefaultScheduledJobFactory.Create(ScheduledJob job)
   at EPiServer.Scheduler.Internal.DefaultScheduledJobExecutor.CreateJobInstance(ScheduledJob job, ScheduledJobTrigger trigger)

**Comment by frederikvig** [comment]
So that's for this particular error. What we need to verify is that the registration actually kicks in, there should be some log entries around that

**Comment by chiching1119** [comment]
Ok thanks! I will add some log around the registration and see. I will give
you an update tomorrow.

**Comment by chiching1119** [comment]
Hi, 

I have added som log around the registration and it seems the registration have actually kicks in. 
`  public class DependencyResolverInitialization : IConfigurableModule
    {
        private static readonly ILog log = LogManager.GetLogger(typeof(DependencyResolverInitialization));

        public void ConfigureContainer(ServiceConfigurationContext context)
        {
            var container = context.StructureMap();
            LogHelper.LogMessage("1",log);
            container.Configure(ConfigureContainer);
            LogHelper.LogMessage("2", log);
            var resolver = new StructureMapDependencyResolver(container);
            LogHelper.LogMessage("3", log);
            DependencyResolver.SetResolver(resolver);
            LogHelper.LogMessage("4", log);
            GlobalConfiguration.Configuration.DependencyResolver = resolver;
        }

        private static void ConfigureContainer(ConfigurationExpression container)
        {
            //Swap out the default ContentRenderer for our custom
            container.For<ICartService>().Use<CartService>();
            container.For<IPricingService>().Use<PricingService>();
            container.For<ICurrencyService>().Use<CurrencyService>();
            container.For<IAddressService>().Use<AddressService>();
            container.For<IPaymentService>().Use<PaymentService>();
            container.For<FeedBuilder>().Use<EpiFeedBuilder>();
            LogHelper.LogMessage("5", log);
        }

        public void Initialize(InitializationEngine context)
        {
        }

        public void Uninitialize(InitializationEngine context)
        {
        }

        public void Preload(string[] parameters)
        {
        }
    }`
 
I am not sure if the code is implemented correctly. why does it empty is the Initialize method.

**Comment by valdisiljuconoks** [comment]
Closed due to inactivity. If you are still experiencing this issue - please reopen.
